# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroAsist', '0002_auto_20161027_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_familiar',
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_hc',
            field=models.CharField(blank=True, help_text='Numero historia clinica en archivo físico', max_length=10, null=True),
        ),
    ]
