# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroAsist', '0003_auto_20161029_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='familiares',
            field=models.ManyToManyField(blank=True, related_name='_paciente_familiares_+', to='CentroAsist.Paciente'),
        ),
    ]
