# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroAsist', '0005_auto_20161029_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='busqueda_HC',
        ),
        migrations.AddField(
            model_name='registrohc',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CentroAsist.Profesional'),
        ),
        migrations.AlterField(
            model_name='registrohc',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CentroAsist.Paciente'),
            preserve_default=False,
        ),
    ]
